version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.5.16
    container_name: db_wikut
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "wikut"
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_wikut
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
    networks:
      - dev

networks:
  dev:

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
