version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  #mailer:
    #image: schickling/mailcatcher
    #container_name: mail_wikut
    #ports: [1025, 1080]
###< symfony/mailer ###
