INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KH','EN','Cambodia','Cambodge','Camboya',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CH','FR','Switzerland','Suisse','Suiza',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NG','EN','Nigeria','Nigéria','Nigeria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CZ','EN','Czech Republic','République tchèque','República Checa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('UZ','EN','Uzbekistan','Ouzbékistan','Uzbekistán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GF','FR','French Guiana','Guyane française','Guayana Francesa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('DE','EN','Germany','Allemagne','Alemania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BH','EN','Bahrain','Bahreïn','Bahrein',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MH','EN','Marshall Islands','Iles Marshall','Islas Marshall',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('VE','SP','Venezuela, Bolivarian Rep. of','Venezuela, Rép. bolivarienne du','Venezuela, Rep. Bolivariana de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('RE','FR','Réunion','Réunion','Reunión',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GY','EN','Guyana','Guyana','Guyana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BI','FR','Burundi','Burundi','Burundi',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KI','EN','Kiribati','Kiribati','Kiribati',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('JO','EN','Jordan','Jordanie','Jordania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AU','EN','Australia','Australie','Australia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('EH','SP','Western Sahara','Sahara occidental','Sahara Occidental',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GE','EN','Georgia','Géorgie','Georgia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LU','FR','Luxembourg','Luxembourg','Luxemburgo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('JP','EN','Japan','Japon','Japón',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BO','SP','Bolivia','Bolivie','Bolivia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('D2','EN','Germany, Fed. Rep. of before 3.10.1990','Allemagne, Rép. Féd. avant le 3.10.1990','Alemania, Rep. Fed. antes del 3.10.1990',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AL','EN','Albania','Albanie','Albania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ME','EN','Montenegro','Monténégro','Montenegro',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('US','EN','United States','Etats-Unis','Estados Unidos',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BA','EN','Bosnia and Herzegovina','Bosnie-Herzégovine','Bosnia y Herzegovina',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PG','EN','Papua New Guinea','Papouasie-Nouvelle-Guinée','Papua Nueva Guinea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LV','EN','Latvia','Lettonie','Letonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IR','EN','Iran, Islamic Rep. of','Iran, Rép. islamique d''','Irán, Rep. Islámica del',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GM','EN','Gambia','Gambie','Gambia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NC','FR','New Caledonia','Nouvelle-Calédonie','Nueva Caledonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KS','EN','Kosovo','Kosovo','Kosovo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BN','EN','Brunei Darussalam','Brunéi Darussalam','Brunei Darussalam',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BR','SP','Brazil','Brésil','Brasil',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NO','EN','Norway','Norvège','Noruega',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GA','FR','Gabon','Gabon','Gabón',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('T2','EN','Tanzania (Zanzibar)','Tanzanie (Zanzibar)','Tanzanía (Zanzíbar)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IQ','EN','Iraq','Iraq','Iraq',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SU','EN','USSR','URSS','URSS',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('DJ','FR','Djibouti','Djibouti','Djibouti',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PL','EN','Poland','Pologne','Polonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SO','EN','Somalia','Somalie','Somalia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SR','EN','Suriname','Suriname','Suriname',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ZM','EN','Zambia','Zambie','Zambia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AN','EN','Netherlands Antilles','Antilles néerlandaises','Antillas Neerlandesas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('Y3','EN','Yugoslavia, The former Socialist Fed. Rep. of','Yougoslavie, Ancienne Rép. socialiste de','Yugoslavia, Antigua Rep. Fed. socialista',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MM','EN','Myanmar','Myanmar','Myanmar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GP','FR','Guadeloupe','Guadeloupe','Guadalupe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MX','SP','Mexico','Mexique','México',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MU','EN','Mauritius','Maurice','Mauricio',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SA','EN','Saudi Arabia','Arabie saoudite','Arabia Saudita',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LK','EN','Sri Lanka','Sri Lanka','Sri Lanka',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NR','EN','Nauru','Nauru','Nauru',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MK','EN','Macedonia, The former Yugoslav Rep. of','Macédoine, Ex-Rép. yougoslave de','Macedonia, Ex Rep. Yugoslava de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('D1','EN','Germany, The former German Dem. Rep.','Allemagne, Ancienne Rép. dém. allemande','Alemania, Antigua Rep. Dem. Alemana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GI','EN','Gibraltar','Gibraltar','Gibraltar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TW','EN','Taiwan, China','Taïwan, Chine','Taiwan, China',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CD','FR','Congo, Democratic Republic of the','Congo, Rép. dém. du','Congo, Rep. Dem. del',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MP','EN','Northern Mariana Islands','Iles Mariannes du Nord','Islas Marianas del Norte',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ET','EN','Ethiopia','Ethiopie','Etiopía',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AT','EN','Austria','Autriche','Austria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CN','EN','China','Chine','China',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NL','EN','Netherlands','Pays-Bas','Países Bajos',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TN','FR','Tunisia','Tunisie','Túnez',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CY','EN','Cyprus','Chypre','Chipre',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('M3','EN','Malaysia: Sarawak','Malaisie: Sarawak','Malasia: Sarawak',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KP','EN','Korea, Dem. People''s Rep. of','Corée, Rép. pop. dém. de','Corea, Rep. Pop. Dem. de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LB','FR','Lebanon','Liban','Líbano',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LR','EN','Liberia','Libéria','Liberia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AZ','EN','Azerbaijan','Azerbaïdjan','Azerbaiyán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ES','SP','Spain','Espagne','España',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('QA','EN','Qatar','Qatar','Qatar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('OM','EN','Oman','Oman','Omán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SK','EN','Slovakia','Slovaquie','Eslovaquia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CV','FR','Cape Verde','Cap-Vert','Cabo Verde',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GB','EN','United Kingdom','Royaume-Uni','Reino Unido',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MT','EN','Malta','Malte','Malta',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IL','EN','Israel','Israël','Israel',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LS','EN','Lesotho','Lesotho','Lesotho',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LA','EN','Lao People''s Dem. Rep.','République dém. pop. lao','República Dem. Pop. Lao',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BF','FR','Burkina Faso','Burkina Faso','Burkina Faso',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('VC','EN','Saint Vincent and the Grenadines','Saint-Vincent-et-les Grenadines','San Vicente y las Granadinas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PM','FR','Saint Pierre and Miquelon','Saint-Pierre-et-Miquelon','San Pedro y Miquelón',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SI','EN','Slovenia','Slovénie','Eslovenia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BB','EN','Barbados','Barbade','Barbados',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IE','EN','Ireland','Irlande','Irlanda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CI','FR','Côte d''Ivoire','Côte d''Ivoire','Côte d''Ivoire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('RW','EN','Rwanda','Rwanda','Rwanda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TV','EN','Tuvalu','Tuvalu','Tuvalu',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SM','FR','San Marino','Saint-Marin','San Marino',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ER','EN','Eritrea','Erythrée','Eritrea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GL','EN','Greenland','Groenland','Groenlandia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TM','EN','Turkmenistan','Turkménistan','Turkmenistán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KE','EN','Kenya','Kenya','Kenya',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TJ','EN','Tajikistan','Tadjikistan','Tayikistán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AI','EN','Anguilla','Anguilla','Anguilla',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('FO','EN','Faeroe Islands','Iles Féroé','Islas Feroe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MG','FR','Madagascar','Madagascar','Madagascar',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LI','EN','Liechtenstein','Liechtenstein','Liechtenstein',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SC','EN','Seychelles','Seychelles','Seychelles',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MO','EN','Macau, China','Macao, Chine','Macao, China',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('UG','EN','Uganda','Ouganda','Uganda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MA','FR','Morocco','Maroc','Marruecos',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('T1','EN','Tanzania (Tanganyika)','Tanzanie (Tanganyika)','Tanzanía (Tangañika)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('UA','EN','Ukraine','Ukraine','Ucrania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ZW','EN','Zimbabwe','Zimbabwe','Zimbabwe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SY','EN','Syrian Arab Republic','République arabe syrienne','República Arabe Siria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TO','EN','Tonga','Tonga','Tonga',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SZ','EN','Swaziland','Swaziland','Swazilandia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('WF','FR','Wallis and Futuna Islands','Iles Wallis et Futuna','Islas Wallis y Futuna',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TH','EN','Thailand','Thaïlande','Tailandia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TL','EN','Timor-Leste','Timor-Leste','Timor-Leste',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BE','FR','Belgium','Belgique','Bélgica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IS','EN','Iceland','Islande','Islandia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BG','EN','Bulgaria','Bulgarie','Bulgaria',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SS','EN','South Sudan, The Republic of','Soudan, République du','Sudán, República de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TR','EN','Turkey','Turquie','Turquía',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MW','EN','Malawi','Malawi','Malawi',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GN','FR','Guinea','Guinée','Guinea',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MY','EN','Malaysia','Malaisie','Malasia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IN','EN','India','Inde','India',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('JE','EN','Jersey','Jersey','Jersey',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MS','EN','Montserrat','Montserrat','Montserrat',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MN','EN','Mongolia','Mongolie','Mongolia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('HU','EN','Hungary','Hongrie','Hungría',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ID','EN','Indonesia','Indonésie','Indonesia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BM','EN','Bermuda','Bermudes','Bermudas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('DM','EN','Dominica','Dominique','Dominica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NE','FR','Niger','Niger','Níger',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('FJ','EN','Fiji','Fidji','Fiji',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CM','FR','Cameroon','Cameroun','Camerún',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('DK','EN','Denmark','Danemark','Dinamarca',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('YE','EN','Yemen','Yémen','Yemen',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('M2','EN','Malaysia: Sabah','Malaisie: Sabah','Malasia: Sabah',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IM','EN','Isle of Man','Ile de Man','Isla de Man',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TC','EN','Turks and Caicos Islands','Iles Turques et Caïques','Islas Turcos y Caicos',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LY','EN','Libyan Arab Jamahiriya','Jamahiriya arabe libyenne','Jamahiriya Arabe Libia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('HR','EN','Croatia','Croatie','Croacia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TG','FR','Togo','Togo','Togo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PF','FR','French Polynesia','Polynésie française','Polinesia Francesa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('EG','EN','Egypt','Egypte','Egipto',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('WS','EN','Samoa','Samoa','Samoa',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BY','EN','Belarus','Bélarus','Belarús',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PA','SP','Panama','Panama','Panamá',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('HT','FR','Haiti','Haïti','Haití',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BD','EN','Bangladesh','Bangladesh','Bangladesh',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('VU','EN','Vanuatu','Vanuatu','Vanuatu',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ST','SP','Sao Tome and Principe','Sao Tomé-et-Principe','Santo Tomé y Príncipe',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TD','FR','Chad','Tchad','Chad',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NZ','EN','New Zealand','Nouvelle-Zélande','Nueva Zelandia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CA','EN','Canada','Canada','Canadá',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KG','EN','Kyrgyzstan','Kirghizistan','Kirguistán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('JG','EN','Channel Islands','Iles Anglo-normandes','Islas Anglonormandas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TT','EN','Trinidad and Tobago','Trinité-et-Tobago','Trinidad y Tabago',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GQ','SP','Equatorial Guinea','Guinée équatoriale','Guinea Ecuatorial',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('RU','EN','Russian Federation','Russie, Fédération de','Rusia, Federación de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('VG','EN','British Virgin Islands','Iles Vierges britanniques','Islas Vírgenes británicas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('C1','EN','Czechoslovakia','Tchécoslovaquie','Checoslovaquia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SB','EN','Solomon Islands','Iles Salomon','Islas Salomón',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BW','EN','Botswana','Botswana','Botswana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TK','EN','Tokelau','Tokélaou','Tokelau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('HK','EN','Hong Kong, China','Hong-kong, Chine','Hong Kong, China',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SG','EN','Singapore','Singapour','Singapur',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KR','EN','Korea, Republic of','Corée, République de','Corea, República de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ML','FR','Mali','Mali','Malí',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AS','EN','American Samoa','Samoa américaines','Samoa Americana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LT','EN','Lithuania','Lituanie','Lituania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('ZA','EN','South Africa','Afrique du Sud','Sudáfrica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SH','EN','Saint Helena','Sainte-Hélène','Santa Elena',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NA','EN','Namibia','Namibie','Namibia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AD','FR','Andorra','Andorre','Andorra',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NP','EN','Nepal','Népal','Nepal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('UY','SP','Uruguay','Uruguay','Uruguay',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('LC','EN','Saint Lucia','Sainte-Lucie','Santa Lucía',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AG','EN','Antigua and Barbuda','Antigua-et-Barbuda','Antigua y Barbuda',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AR','SP','Argentina','Argentine','Argentina',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('RO','FR','Romania','Roumanie','Rumania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PS','EN','West Bank and Gaza Strip','Rive occidentale et Bande de Gaza','Ribera occidental y Faja de Gaza',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('JM','EN','Jamaica','Jamaïque','Jamaica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MV','EN','Maldives','Maldives','Maldivas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GW','FR','Guinea-Bissau','Guinée-Bissau','Guinea-Bissau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MR','FR','Mauritania','Mauritanie','Mauritania',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('EC','SP','Ecuador','Equateur','Ecuador',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NI','SP','Nicaragua','Nicaragua','Nicaragua',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CU','SP','Cuba','Cuba','Cuba',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KW','EN','Kuwait','Koweït','Kuwait',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PT','FR','Portugal','Portugal','Portugal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('Y2','EN','Yemen, The former Democratic','Yémen, Ancien Yémen démocratique','Yemen, Antiguo Yemen democrático',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GR','EN','Greece','Grèce','Grecia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('FK','EN','Falkland Islands (Malvinas)','Iles Falkland (Malvinas)','Islas Malvinas (Falkland)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MD','EN','Moldova, Republic of','Moldova, République de','Moldova, República de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GT','SP','Guatemala','Guatemala','Guatemala',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AO','FR','Angola','Angola','Angola',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('VN','EN','Viet Nam','Viet Nam','Viet Nam',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('RS','EN','Serbia','Serbie','Serbia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KM','FR','Comoros','Comores','Comoras',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GH','EN','Ghana','Ghana','Ghana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('TZ','EN','Tanzania, United Republic of','Tanzanie, République-Unie de','Tanzanía, República Unida de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MQ','FR','Martinique','Martinique','Martinica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SD','EN','Sudan, The Republic of','Soudan, République du','Sudán, República de',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NU','EN','Niue','Nioué','Niue',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('D3','EN','Germany, 5 new Länder and Berlin (East)','Allemagne, 5 nouveaux Länder et Berlin-Est','Alemania, 5 nuevos Länder y Berlin Este',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BZ','EN','Belize','Belize','Belice',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('IT','EN','Italy','Italie','Italia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('FI','EN','Finland','Finlande','Finlandia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PY','SP','Paraguay','Paraguay','Paraguay',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AF','EN','Afghanistan','Afghanistan','Afganistán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AE','EN','United Arab Emirates','Emirats arabes unis','Emiratos Arabes Unidos',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PE','SP','Peru','Pérou','Perú',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CG','FR','Congo','Congo','Congo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('HN','SP','Honduras','Honduras','Honduras',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('VI','EN','Virgin Islands (US)','Iles Vierges américaines','Islas Vírgenes (EE.UU.)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CK','EN','Cook Islands','Iles Cook','Islas Cook',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SL','EN','Sierra Leone','Sierra Leone','Sierra Leona',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SN','FR','Senegal','Sénégal','Senegal',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('NF','EN','Norfolk Island','Ile Norfolk','Isla Norfolk',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KN','EN','Saint Kitts and Nevis','Saint-Kitts-et-Nevis','Saint Kitts y Nevis',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BT','EN','Bhutan','Bhoutan','Bhután',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PW','EN','Palau','Palau','Palau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KZ','EN','Kazakhstan','Kazakhstan','Kazajstán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BJ','FR','Benin','Bénin','Benin',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AW','EN','Aruba','Aruba','Aruba',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CS','EN','Serbia and Montenegro','Serbie-et-Monténégro','Serbia y Montenegro',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('DO','SP','Dominican Republic','République dominicaine','República Dominicana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('Y1','EN','Yemen, The former Arab Rep. of','Yémen, Ancienne Rép. arabe du','Yemen, Antigua Rep. Arabe del',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CF','FR','Central African Republic','République centrafricaine','República Centroafricana',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('DZ','FR','Algeria','Algérie','Argelia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GU','EN','Guam','Guam','Guam',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GD','EN','Grenada','Grenade','Granada',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('FR','FR','France','France','Francia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MZ','EN','Mozambique','Mozambique','Mozambique',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('EE','EN','Estonia','Estonie','Estonia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CL','SP','Chile','Chili','Chile',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PR','EN','Puerto Rico','Porto Rico','Puerto Rico',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CR','SP','Costa Rica','Costa Rica','Costa Rica',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('AM','EN','Armenia','Arménie','Armenia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('GG','EN','Guernsey','Guernesey','Guernesey',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('M1','EN','Malaysia: Peninsular Malaysia','Malaisie: Malaisie péninsulaire','Malasia: Malasia Peninsular',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SE','EN','Sweden','Suède','Suecia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PK','EN','Pakistan','Pakistan','Pakistán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('KY','EN','Cayman Islands','Iles Caïmanes','Islas Caimán',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('MC','FR','Monaco','Monaco','Mónaco',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('BS','EN','Bahamas','Bahamas','Bahamas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('E1','EN','Ethiopia (including Eritrea)','Ethiopie (y compris l''Erythrée)','Etiopía (incluyendo Eritrea)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('CO','SP','Colombia','Colombie','Colombia',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('SV','SP','El Salvador','El Salvador','El Salvador',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO country(code,lang,label_en,label_fr,label_es, `created_at`, `updated_at`) VALUES ('PH','EN','Philippines','Philippines','Filipinas',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
