INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KH','EN','Cambodia','Cambodge','Camboya');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CH','FR','Switzerland','Suisse','Suiza');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NG','EN','Nigeria','Nigéria','Nigeria');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CZ','EN','Czech Republic','République tchèque','República Checa');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('UZ','EN','Uzbekistan','Ouzbékistan','Uzbekistán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GF','FR','French Guiana','Guyane française','Guayana Francesa');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('DE','EN','Germany','Allemagne','Alemania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BH','EN','Bahrain','Bahreïn','Bahrein');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MH','EN','Marshall Islands','Iles Marshall','Islas Marshall');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('VE','SP','Venezuela, Bolivarian Rep. of','Venezuela, Rép. bolivarienne du','Venezuela, Rep. Bolivariana de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('RE','FR','Réunion','Réunion','Reunión');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GY','EN','Guyana','Guyana','Guyana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BI','FR','Burundi','Burundi','Burundi');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KI','EN','Kiribati','Kiribati','Kiribati');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('JO','EN','Jordan','Jordanie','Jordania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AU','EN','Australia','Australie','Australia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('EH','SP','Western Sahara','Sahara occidental','Sahara Occidental');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GE','EN','Georgia','Géorgie','Georgia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LU','FR','Luxembourg','Luxembourg','Luxemburgo');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('JP','EN','Japan','Japon','Japón');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BO','SP','Bolivia','Bolivie','Bolivia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('D2','EN','Germany, Fed. Rep. of before 3.10.1990','Allemagne, Rép. Féd. avant le 3.10.1990','Alemania, Rep. Fed. antes del 3.10.1990');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AL','EN','Albania','Albanie','Albania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ME','EN','Montenegro','Monténégro','Montenegro');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('US','EN','United States','Etats-Unis','Estados Unidos');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BA','EN','Bosnia and Herzegovina','Bosnie-Herzégovine','Bosnia y Herzegovina');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PG','EN','Papua New Guinea','Papouasie-Nouvelle-Guinée','Papua Nueva Guinea');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LV','EN','Latvia','Lettonie','Letonia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IR','EN','Iran, Islamic Rep. of','Iran, Rép. islamique d''','Irán, Rep. Islámica del');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GM','EN','Gambia','Gambie','Gambia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NC','FR','New Caledonia','Nouvelle-Calédonie','Nueva Caledonia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KS','EN','Kosovo','Kosovo','Kosovo');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BN','EN','Brunei Darussalam','Brunéi Darussalam','Brunei Darussalam');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BR','SP','Brazil','Brésil','Brasil');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NO','EN','Norway','Norvège','Noruega');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GA','FR','Gabon','Gabon','Gabón');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('T2','EN','Tanzania (Zanzibar)','Tanzanie (Zanzibar)','Tanzanía (Zanzíbar)');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IQ','EN','Iraq','Iraq','Iraq');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SU','EN','USSR','URSS','URSS');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('DJ','FR','Djibouti','Djibouti','Djibouti');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PL','EN','Poland','Pologne','Polonia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SO','EN','Somalia','Somalie','Somalia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SR','EN','Suriname','Suriname','Suriname');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ZM','EN','Zambia','Zambie','Zambia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AN','EN','Netherlands Antilles','Antilles néerlandaises','Antillas Neerlandesas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('Y3','EN','Yugoslavia, The former Socialist Fed. Rep. of','Yougoslavie, Ancienne Rép. socialiste de','Yugoslavia, Antigua Rep. Fed. socialista');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MM','EN','Myanmar','Myanmar','Myanmar');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GP','FR','Guadeloupe','Guadeloupe','Guadalupe');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MX','SP','Mexico','Mexique','México');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MU','EN','Mauritius','Maurice','Mauricio');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SA','EN','Saudi Arabia','Arabie saoudite','Arabia Saudita');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LK','EN','Sri Lanka','Sri Lanka','Sri Lanka');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NR','EN','Nauru','Nauru','Nauru');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MK','EN','Macedonia, The former Yugoslav Rep. of','Macédoine, Ex-Rép. yougoslave de','Macedonia, Ex Rep. Yugoslava de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('D1','EN','Germany, The former German Dem. Rep.','Allemagne, Ancienne Rép. dém. allemande','Alemania, Antigua Rep. Dem. Alemana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GI','EN','Gibraltar','Gibraltar','Gibraltar');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TW','EN','Taiwan, China','Taïwan, Chine','Taiwan, China');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CD','FR','Congo, Democratic Republic of the','Congo, Rép. dém. du','Congo, Rep. Dem. del');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MP','EN','Northern Mariana Islands','Iles Mariannes du Nord','Islas Marianas del Norte');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ET','EN','Ethiopia','Ethiopie','Etiopía');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AT','EN','Austria','Autriche','Austria');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CN','EN','China','Chine','China');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NL','EN','Netherlands','Pays-Bas','Países Bajos');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TN','FR','Tunisia','Tunisie','Túnez');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CY','EN','Cyprus','Chypre','Chipre');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('M3','EN','Malaysia: Sarawak','Malaisie: Sarawak','Malasia: Sarawak');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KP','EN','Korea, Dem. People''s Rep. of','Corée, Rép. pop. dém. de','Corea, Rep. Pop. Dem. de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LB','FR','Lebanon','Liban','Líbano');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LR','EN','Liberia','Libéria','Liberia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AZ','EN','Azerbaijan','Azerbaïdjan','Azerbaiyán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ES','SP','Spain','Espagne','España');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('QA','EN','Qatar','Qatar','Qatar');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('OM','EN','Oman','Oman','Omán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SK','EN','Slovakia','Slovaquie','Eslovaquia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CV','FR','Cape Verde','Cap-Vert','Cabo Verde');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GB','EN','United Kingdom','Royaume-Uni','Reino Unido');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MT','EN','Malta','Malte','Malta');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IL','EN','Israel','Israël','Israel');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LS','EN','Lesotho','Lesotho','Lesotho');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LA','EN','Lao People''s Dem. Rep.','République dém. pop. lao','República Dem. Pop. Lao');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BF','FR','Burkina Faso','Burkina Faso','Burkina Faso');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('VC','EN','Saint Vincent and the Grenadines','Saint-Vincent-et-les Grenadines','San Vicente y las Granadinas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PM','FR','Saint Pierre and Miquelon','Saint-Pierre-et-Miquelon','San Pedro y Miquelón');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SI','EN','Slovenia','Slovénie','Eslovenia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BB','EN','Barbados','Barbade','Barbados');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IE','EN','Ireland','Irlande','Irlanda');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CI','FR','Côte d''Ivoire','Côte d''Ivoire','Côte d''Ivoire');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('RW','EN','Rwanda','Rwanda','Rwanda');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TV','EN','Tuvalu','Tuvalu','Tuvalu');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SM','FR','San Marino','Saint-Marin','San Marino');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ER','EN','Eritrea','Erythrée','Eritrea');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GL','EN','Greenland','Groenland','Groenlandia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TM','EN','Turkmenistan','Turkménistan','Turkmenistán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KE','EN','Kenya','Kenya','Kenya');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TJ','EN','Tajikistan','Tadjikistan','Tayikistán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AI','EN','Anguilla','Anguilla','Anguilla');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('FO','EN','Faeroe Islands','Iles Féroé','Islas Feroe');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MG','FR','Madagascar','Madagascar','Madagascar');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LI','EN','Liechtenstein','Liechtenstein','Liechtenstein');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SC','EN','Seychelles','Seychelles','Seychelles');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MO','EN','Macau, China','Macao, Chine','Macao, China');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('UG','EN','Uganda','Ouganda','Uganda');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MA','FR','Morocco','Maroc','Marruecos');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('T1','EN','Tanzania (Tanganyika)','Tanzanie (Tanganyika)','Tanzanía (Tangañika)');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('UA','EN','Ukraine','Ukraine','Ucrania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ZW','EN','Zimbabwe','Zimbabwe','Zimbabwe');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SY','EN','Syrian Arab Republic','République arabe syrienne','República Arabe Siria');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TO','EN','Tonga','Tonga','Tonga');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SZ','EN','Swaziland','Swaziland','Swazilandia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('WF','FR','Wallis and Futuna Islands','Iles Wallis et Futuna','Islas Wallis y Futuna');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TH','EN','Thailand','Thaïlande','Tailandia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TL','EN','Timor-Leste','Timor-Leste','Timor-Leste');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BE','FR','Belgium','Belgique','Bélgica');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IS','EN','Iceland','Islande','Islandia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BG','EN','Bulgaria','Bulgarie','Bulgaria');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SS','EN','South Sudan, The Republic of','Soudan, République du','Sudán, República de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TR','EN','Turkey','Turquie','Turquía');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MW','EN','Malawi','Malawi','Malawi');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GN','FR','Guinea','Guinée','Guinea');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MY','EN','Malaysia','Malaisie','Malasia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IN','EN','India','Inde','India');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('JE','EN','Jersey','Jersey','Jersey');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MS','EN','Montserrat','Montserrat','Montserrat');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MN','EN','Mongolia','Mongolie','Mongolia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('HU','EN','Hungary','Hongrie','Hungría');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ID','EN','Indonesia','Indonésie','Indonesia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BM','EN','Bermuda','Bermudes','Bermudas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('DM','EN','Dominica','Dominique','Dominica');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NE','FR','Niger','Niger','Níger');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('FJ','EN','Fiji','Fidji','Fiji');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CM','FR','Cameroon','Cameroun','Camerún');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('DK','EN','Denmark','Danemark','Dinamarca');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('YE','EN','Yemen','Yémen','Yemen');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('M2','EN','Malaysia: Sabah','Malaisie: Sabah','Malasia: Sabah');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IM','EN','Isle of Man','Ile de Man','Isla de Man');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TC','EN','Turks and Caicos Islands','Iles Turques et Caïques','Islas Turcos y Caicos');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LY','EN','Libyan Arab Jamahiriya','Jamahiriya arabe libyenne','Jamahiriya Arabe Libia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('HR','EN','Croatia','Croatie','Croacia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TG','FR','Togo','Togo','Togo');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PF','FR','French Polynesia','Polynésie française','Polinesia Francesa');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('EG','EN','Egypt','Egypte','Egipto');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('WS','EN','Samoa','Samoa','Samoa');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BY','EN','Belarus','Bélarus','Belarús');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PA','SP','Panama','Panama','Panamá');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('HT','FR','Haiti','Haïti','Haití');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BD','EN','Bangladesh','Bangladesh','Bangladesh');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('VU','EN','Vanuatu','Vanuatu','Vanuatu');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ST','SP','Sao Tome and Principe','Sao Tomé-et-Principe','Santo Tomé y Príncipe');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TD','FR','Chad','Tchad','Chad');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NZ','EN','New Zealand','Nouvelle-Zélande','Nueva Zelandia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CA','EN','Canada','Canada','Canadá');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KG','EN','Kyrgyzstan','Kirghizistan','Kirguistán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('JG','EN','Channel Islands','Iles Anglo-normandes','Islas Anglonormandas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TT','EN','Trinidad and Tobago','Trinité-et-Tobago','Trinidad y Tabago');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GQ','SP','Equatorial Guinea','Guinée équatoriale','Guinea Ecuatorial');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('RU','EN','Russian Federation','Russie, Fédération de','Rusia, Federación de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('VG','EN','British Virgin Islands','Iles Vierges britanniques','Islas Vírgenes británicas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('C1','EN','Czechoslovakia','Tchécoslovaquie','Checoslovaquia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SB','EN','Solomon Islands','Iles Salomon','Islas Salomón');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BW','EN','Botswana','Botswana','Botswana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TK','EN','Tokelau','Tokélaou','Tokelau');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('HK','EN','Hong Kong, China','Hong-kong, Chine','Hong Kong, China');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SG','EN','Singapore','Singapour','Singapur');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KR','EN','Korea, Republic of','Corée, République de','Corea, República de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ML','FR','Mali','Mali','Malí');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AS','EN','American Samoa','Samoa américaines','Samoa Americana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LT','EN','Lithuania','Lituanie','Lituania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('ZA','EN','South Africa','Afrique du Sud','Sudáfrica');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SH','EN','Saint Helena','Sainte-Hélène','Santa Elena');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NA','EN','Namibia','Namibie','Namibia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AD','FR','Andorra','Andorre','Andorra');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NP','EN','Nepal','Népal','Nepal');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('UY','SP','Uruguay','Uruguay','Uruguay');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('LC','EN','Saint Lucia','Sainte-Lucie','Santa Lucía');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AG','EN','Antigua and Barbuda','Antigua-et-Barbuda','Antigua y Barbuda');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AR','SP','Argentina','Argentine','Argentina');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('RO','FR','Romania','Roumanie','Rumania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PS','EN','West Bank and Gaza Strip','Rive occidentale et Bande de Gaza','Ribera occidental y Faja de Gaza');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('JM','EN','Jamaica','Jamaïque','Jamaica');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MV','EN','Maldives','Maldives','Maldivas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GW','FR','Guinea-Bissau','Guinée-Bissau','Guinea-Bissau');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MR','FR','Mauritania','Mauritanie','Mauritania');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('EC','SP','Ecuador','Equateur','Ecuador');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NI','SP','Nicaragua','Nicaragua','Nicaragua');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CU','SP','Cuba','Cuba','Cuba');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KW','EN','Kuwait','Koweït','Kuwait');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PT','FR','Portugal','Portugal','Portugal');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('Y2','EN','Yemen, The former Democratic','Yémen, Ancien Yémen démocratique','Yemen, Antiguo Yemen democrático');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GR','EN','Greece','Grèce','Grecia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('FK','EN','Falkland Islands (Malvinas)','Iles Falkland (Malvinas)','Islas Malvinas (Falkland)');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MD','EN','Moldova, Republic of','Moldova, République de','Moldova, República de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GT','SP','Guatemala','Guatemala','Guatemala');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AO','FR','Angola','Angola','Angola');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('VN','EN','Viet Nam','Viet Nam','Viet Nam');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('RS','EN','Serbia','Serbie','Serbia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KM','FR','Comoros','Comores','Comoras');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GH','EN','Ghana','Ghana','Ghana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('TZ','EN','Tanzania, United Republic of','Tanzanie, République-Unie de','Tanzanía, República Unida de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MQ','FR','Martinique','Martinique','Martinica');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SD','EN','Sudan, The Republic of','Soudan, République du','Sudán, República de');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NU','EN','Niue','Nioué','Niue');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('D3','EN','Germany, 5 new Länder and Berlin (East)','Allemagne, 5 nouveaux Länder et Berlin-Est','Alemania, 5 nuevos Länder y Berlin Este');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BZ','EN','Belize','Belize','Belice');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('IT','EN','Italy','Italie','Italia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('FI','EN','Finland','Finlande','Finlandia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PY','SP','Paraguay','Paraguay','Paraguay');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AF','EN','Afghanistan','Afghanistan','Afganistán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AE','EN','United Arab Emirates','Emirats arabes unis','Emiratos Arabes Unidos');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PE','SP','Peru','Pérou','Perú');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CG','FR','Congo','Congo','Congo');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('HN','SP','Honduras','Honduras','Honduras');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('VI','EN','Virgin Islands (US)','Iles Vierges américaines','Islas Vírgenes (EE.UU.)');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CK','EN','Cook Islands','Iles Cook','Islas Cook');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SL','EN','Sierra Leone','Sierra Leone','Sierra Leona');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SN','FR','Senegal','Sénégal','Senegal');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('NF','EN','Norfolk Island','Ile Norfolk','Isla Norfolk');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KN','EN','Saint Kitts and Nevis','Saint-Kitts-et-Nevis','Saint Kitts y Nevis');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BT','EN','Bhutan','Bhoutan','Bhután');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PW','EN','Palau','Palau','Palau');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KZ','EN','Kazakhstan','Kazakhstan','Kazajstán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BJ','FR','Benin','Bénin','Benin');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AW','EN','Aruba','Aruba','Aruba');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CS','EN','Serbia and Montenegro','Serbie-et-Monténégro','Serbia y Montenegro');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('DO','SP','Dominican Republic','République dominicaine','República Dominicana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('Y1','EN','Yemen, The former Arab Rep. of','Yémen, Ancienne Rép. arabe du','Yemen, Antigua Rep. Arabe del');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CF','FR','Central African Republic','République centrafricaine','República Centroafricana');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('DZ','FR','Algeria','Algérie','Argelia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GU','EN','Guam','Guam','Guam');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GD','EN','Grenada','Grenade','Granada');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('FR','FR','France','France','Francia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MZ','EN','Mozambique','Mozambique','Mozambique');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('EE','EN','Estonia','Estonie','Estonia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CL','SP','Chile','Chili','Chile');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PR','EN','Puerto Rico','Porto Rico','Puerto Rico');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CR','SP','Costa Rica','Costa Rica','Costa Rica');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('AM','EN','Armenia','Arménie','Armenia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('GG','EN','Guernsey','Guernesey','Guernesey');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('M1','EN','Malaysia: Peninsular Malaysia','Malaisie: Malaisie péninsulaire','Malasia: Malasia Peninsular');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SE','EN','Sweden','Suède','Suecia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PK','EN','Pakistan','Pakistan','Pakistán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('KY','EN','Cayman Islands','Iles Caïmanes','Islas Caimán');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('MC','FR','Monaco','Monaco','Mónaco');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('BS','EN','Bahamas','Bahamas','Bahamas');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('E1','EN','Ethiopia (including Eritrea)','Ethiopie (y compris l''Erythrée)','Etiopía (incluyendo Eritrea)');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('CO','SP','Colombia','Colombie','Colombia');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('SV','SP','El Salvador','El Salvador','El Salvador');
INSERT INTO country(code,lang,label_en,label_fr,label_es) VALUES ('PH','EN','Philippines','Philippines','Filipinas');
